### ISSUE TITLE
Regular automatic updates of isil2wikidata.csv

### ISSUE THREAD

**Issue by acka47** [hbz/lookup-tables#7]
The content of https://github.com/hbz/lookup-tables/blob/master/data/isil2wikidata.csv is based on this wikidata query: http://tinyurl.com/l6uz2gz

It would make sense to establish some kind if automatic update procedure for the mapping file.

**Comment by acka47** [comment]
You can get the (unsorted and with named columns) tsv via `curl -H "Accept: text/tab-separated-values" "https://query.wikidata.org/sparql?query=SELECT%20%3Fisil%20%3Fitem%0AWHERE%0A%7B%0A%20%20%3Fitem%20wdt%3AP791%20%3Fisil%20%20.%0A%20%20FILTER%20%28regex%28%3Fisil%2C%20%22%28AT%7CCH%7CDE%29-.%2a%22%29%29.%0A%7D"`.

**Comment by dr0i** [comment]
Script is cron-scheduled like this:

> 00 4 * * * /home/hduser/git/lookup-tables/docs/isil2wikidata.sh; git add isil2wikidata.csv; git commit -m "Update isil2wikidata"; git push origin master

See https://github.com/hbz/lookup-tables/commit/948ca5ac4b38e8fa501ca8ba246fc68f401d3fa9 as an example of how such an automatic commit looks like.

**Comment by dr0i** [comment]
Reopend for review by @acka47 to acknowledge and maybe check somday if this is working.

**Comment by acka47** [comment]
Looks good. But I wonder why the user is called "Hadoop". This is confusing. However, automatic updates seem to be broken like @dr0i suspected in https://github.com/hbz/lookup-tables/pull/8#issuecomment-325710060. Will open an issue for this.

**Comment by dr0i** [comment]
The author's name "hadoop" is part of the history of this server's life. As the name can be set at willing I set it to `isil2wikidata.sh <crontab@weywot1`. Hope this is less confusing.
