### ISSUE TITLE
Add code that creates isil2wikidata.csv

### ISSUE THREAD

**Issue by fsteeg** [hbz/lookup-tables#9]
As discussed offline, we should add the code that creates the `isil2wikidata.csv` file.

See:

https://github.com/hbz/lookup-tables/issues/7
https://github.com/hbz/lobid-organisations/pull/427

**Comment by dr0i** [comment]
This script already exists - admittedly the directory is not very properly named: https://github.com/hbz/lookup-tables/blob/master/docs/isil2wikidata.sh
